//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Employee
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Employee()
    {
        this.EmployeeRequests = new HashSet<EmployeeRequest>();
        this.EmployeePTOHistories = new HashSet<EmployeePTOHistory>();
    }

    public int EmployeeId { get; set; }
    public string EmployeeName { get; set; }
    public int EmployeeRoleId { get; set; }

    public virtual EmployeeRole EmployeeRole { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<EmployeeRequest> EmployeeRequests { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<EmployeePTOHistory> EmployeePTOHistories { get; set; }
}

public partial class EmployeePTOHistory
{
    public int EmployeePTOHistoryID { get; set; }
    public int EmployeeID { get; set; }
    public System.DateTime StartDate { get; set; }
    public System.DateTime EndDate { get; set; }
    public decimal PTOAmount { get; set; }
    public string Description { get; set; }
    public decimal ResultingPTOBalance { get; set; }

    public virtual Employee Employee { get; set; }
}

public partial class EmployeeRequest
{
    public int EmployeeRequestId { get; set; }
    public int EmployeeId { get; set; }
    public System.DateTime StartDate { get; set; }
    public System.DateTime EndDate { get; set; }
    public decimal PTOAmount { get; set; }
    public string Description { get; set; }

    public virtual Employee Employee { get; set; }
}

public partial class EmployeeRole
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public EmployeeRole()
    {
        this.Employees = new HashSet<Employee>();
    }

    public int EmployeeRoleId { get; set; }
    public string RoleName { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Employee> Employees { get; set; }
}
